export const HOME_PAGE_IMAGES_AMOUNT_TO_LOAD = 30;
export const HOME_PAGE_COLUMNS_COUNT = 3;
export const LIKES_PAGE_COLUMNS_COUNT = 4;
export const THUMBNAIL_IMG_QUALITY = "100";
export const FULL_IMG_QUALITY = "100";
